name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'  # Use Node.js 22

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build the project
      run: npm run build

    - name: Install gh-pages locally
      run: npm install gh-pages --save-dev

    - name: Deploy to GitHub Pages
      run: |
        npm run build
        npx gh-pages -d dist -r https://github.com/${{ github.repository }}.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
